# jobgraph enforces parent images to be pinned with a sha256.
# Run `jobgraph update-dependencies` to pin all docker images to newer hashes
FROM docker/whalesay@sha256:178598e51a26abbc958b8a2e48825c90bc22e641de3d31e18aaf55f3258ba93b

CMD ["cowsay", "Hello from the docker image built by jobgraph!"]
