# This stage ensure your jobgraph definitions are correctly linted.
# Modify this current file at your own risks.
---
loader: jobgraph.loader.transform:loader

transforms:
- jobgraph.transforms.job:transforms

# You can split a stage into multiple files
jobs_from:
- dockerfiles.yml
- python.yml
- yaml.yml

job_defaults:
    runner_alias: t-linux
    timeout: 3 minutes
    variables:
        JOBGRAPH_ROOT_DIR: $CI_PROJECT_DIR/gitlab-ci
