# This stage ensure your jobgraph definitions are correctly linted.
# Modify this current file at your own risks.
---
job_defaults:
    image: {"docker_image_reference": "<jobgraph_tests>"}
    optimization:
        skip_unless_changed:
        - "gitlab-ci/**/*.yml"

yamllint:
    description: "Run `yamllint` to validate the latest changes"
    script: yamllint --strict "$JOBGRAPH_ROOT_DIR"
