---
loader: jobgraph.loader.transform:loader

transforms:
- jobgraph.transforms.job:transforms


jobs:
    hello_world_from_a_job:
        description: >
            This job uses the `hello_world` image defined in `gitlab-ci/stages/docker_image/stage.yml`.
            Jobgraph automatically links this job with the other one with a hash that represents the
            docker context.
        image: {in_tree: hello_world}
        runner_alias: misc
        script:
        - cowsay 'Hello from a job!'
