---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:1ff5e500e2d42048923c1243ad26691c83c65406a33086f56e02e4fb2d43ecd8
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
        jobgraph: registry.gitlab.com/johanlorenzo/jobgraph/decision:c0e1b1ab8e1eb82608e92b49c74508ad6726d0dc9aead22724857d543bbbd2db@sha256:b55f8c7185bab4c3237c1134e0732fa7a45b73c269066a0c6d5c286fd0d54318
gitlab:
    project_id: 31658668
    root_url: https://gitlab.com
job_defaults:
    retry:
        max: 2
        when:
        - runner_system_failure
        - stale_schedule
        - stuck_or_timeout_failure
        - unknown_failure
    timeout: 5 minutes
    variables:
        ARTIFACT_DOWNLOAD_ATTEMPTS: 3
        GET_SOURCES_ATTEMPTS: 3
        RESTORE_CACHE_ATTEMPTS: 3
jobgraph: {}
runners:
    aliases:
        images:
            os: linux
            runner_tag: gitlab-org-docker
        misc:
            os: linux
            runner_tag: gitlab-org-docker
        t-linux:
            os: linux
            runner_tag: gitlab-org-docker
