---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:1ff5e500e2d42048923c1243ad26691c83c65406a33086f56e02e4fb2d43ecd8
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
        jobgraph_schedules: registry.gitlab.com/johanlorenzo/jobgraph/jobgraph_schedules:26a7195a24d4ee43d44f4dad193fb2dea42a5c20021dfb780808392d09542a0f@sha256:5bf4ecfe5793073e084d5438277fbcf52787632d83ed7801792a157ffa7446ba
gitlab:
    project_id: 31658668
    root_url: https://gitlab.com
job_defaults:
    retry:
        max: 2
        when:
        - runner_system_failure
        - stale_schedule
        - stuck_or_timeout_failure
        - unknown_failure
    timeout: 5 minutes
    variables:
        ARTIFACT_DOWNLOAD_ATTEMPTS: 3
        GET_SOURCES_ATTEMPTS: 3
        RESTORE_CACHE_ATTEMPTS: 3
jobgraph: {}
runners:
    aliases:
        images:
            os: linux
            runner_tag: gitlab-org-docker
        misc:
            os: linux
            runner_tag: gitlab-org-docker
        t-linux:
            os: linux
            runner_tag: gitlab-org-docker
