---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:1ff5e500e2d42048923c1243ad26691c83c65406a33086f56e02e4fb2d43ecd8
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
        jobgraph: registry.gitlab.com/johanlorenzo/jobgraph/decision:d45c6452204a2901ffbfa2698cc6dc50b332de6495b4b28a8b309869d37a3228@sha256:255b30244599dfca0cff48942430ac93d7ba60fe3d211b4de05ada21df55cb65
        jobgraph_tests: registry.gitlab.com/johanlorenzo/jobgraph/python_test:83dea63b766fe18ee11f9b46f42183ba832e8d14c3402ab33f223670cc7d296d@sha256:4aad5f1f0137bc8118ea925516a2b04534f1e983f23059bbe9ae7909fb719bf4
gitlab:
    project_id: 31658668
    root_url: https://gitlab.com
job_defaults:
    retry:
        max: 2
        when:
        - runner_system_failure
        - stale_schedule
        - stuck_or_timeout_failure
        - unknown_failure
    timeout: 5 minutes
    variables:
        ARTIFACT_DOWNLOAD_ATTEMPTS: 3
        GET_SOURCES_ATTEMPTS: 3
        RESTORE_CACHE_ATTEMPTS: 3
jobgraph:
    decision_parameters: local_jobgraph.parameters:get_decision_parameters
    register: local_jobgraph:register
runners:
    aliases:
        images:
            os: linux
            runner_tag: gitlab-org-docker
        misc:
            os: linux
            runner_tag: gitlab-org-docker
        t-linux:
            os: linux
            runner_tag: gitlab-org-docker
