---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:1ff5e500e2d42048923c1243ad26691c83c65406a33086f56e02e4fb2d43ecd8
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
        jobgraph: registry.gitlab.com/johanlorenzo/jobgraph/decision:b1939f747425444e4c4975ae5aeffd6ba2f1fd1aa90d716696dd52b227af4122@sha256:28d24e50bafe293424c6e26a0dfe08fe7d82efabe79ef7d953e73df23b7296f7
gitlab:
    project_id: 31658668
    root_url: https://gitlab.com
job_defaults:
    retry:
        max: 2
        when:
        - runner_system_failure
        - stale_schedule
        - stuck_or_timeout_failure
        - unknown_failure
    timeout: 5 minutes
    variables:
        ARTIFACT_DOWNLOAD_ATTEMPTS: 3
        GET_SOURCES_ATTEMPTS: 3
        RESTORE_CACHE_ATTEMPTS: 3
jobgraph:
    decision_parameters: local_jobgraph.parameters:get_decision_parameters
    register: local_jobgraph:register
runners:
    aliases:
        images:
            os: linux
            runner_tag: gitlab-org-docker
        misc:
            os: linux
            runner_tag: gitlab-org-docker
        t-linux:
            os: linux
            runner_tag: gitlab-org-docker
