---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:4e04836731b7100e8bd5e0b35756f53d0b6211ddb3cc7ec326ae3640adcfa004
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
        jobgraph: registry.gitlab.com/johanlorenzo/jobgraph/decision:latest@sha256:a967a22d387246a8c6fe3a968bb73ea8527a5d023a0527c5dadb521f9435b3cc
        jobgraph_tests: registry.gitlab.com/johanlorenzo/jobgraph/python_test:latest@sha256:01c66ecdcbc8dad02ffb17f17e5858e43377d66ff29c6ff27dd63d9795246a07
gitlab:
    project_id: 31658668
    root_url: https://gitlab.com
job_defaults:
    retry:
        max: 2
        when:
        - runner_system_failure
        - stale_schedule
        - stuck_or_timeout_failure
        - unknown_failure
    timeout: 5 minutes
    variables:
        ARTIFACT_DOWNLOAD_ATTEMPTS: 3
        GET_SOURCES_ATTEMPTS: 3
        RESTORE_CACHE_ATTEMPTS: 3
jobgraph:
    decision_parameters: local_jobgraph.parameters:get_decision_parameters
    register: local_jobgraph:register
runners:
    aliases:
        images:
            os: linux
            runner_tag: gitlab-org-docker
        misc:
            os: linux
            runner_tag: gitlab-org-docker
        t-linux:
            os: linux
            runner_tag: gitlab-org-docker
