---
jobs:
    single_job:
        cron: 00 12 * * 1
        description: Schedule a single targeted job each Monday, noon UTC.
        target_jobs_method: single_job_on_given_schedule
    update_dependencies:
        cron: 00 12 * * 3
        description: "Update jobgraph dependencies (e.g.: Docker images) each Wednesday, UTC"
        # This target_jobs_method is provided by upstream jobgraph
        target_jobs_method: jobgraph_updates
